config/routes.rb
Schedulizer::Application.routes.draw do
  resources :events
  resources :employees
  resources :sessions, only: [:new, :create, :destroy]
  resources :event_employees, only: [:create, :destroy]
  resources :test
  root 'events#index'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/api/events', to: API::EventsAPIController.action(:index)
  post '/api/events/destroy', to: API::EventsAPIController.action(:destroy)
  post '/api/events/create', to: API::EventsAPIController.action(:create)
  post '/api/events/update', to: API::EventsAPIController.action(:update)
  get '/api/event_employees', to: API::EventEmployeesAPIController.action(:index)
  post '/api/event_employees/destroy', to: API::EventEmployeesAPIController.action(:destroy)
  post '/api/event_employees/create', to: API::EventEmployeesAPIController.action(:create)
  post '/api/event_employees/update', to: API::EventEmployeesAPIController.action(:update)

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_employees, foreign_key: "event_id", dependent: :destroy
  has_many :workers, through: :event_employees, source: :employee
  default_scope -> { order('date DESC') }
  validates :place, presence: true, length: { maximum: 100 }
  validates :date, presence: true
  validates :start, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_employee
  before_action :exec, only: [:new, :create, :destroy]
  before_action :not_testing

  def index
    @events = Event.paginate(page: params[:page])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event added to calendar."
    end
    render 'index'
  end

  def edit
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
    end
    render 'index'
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to events_url
  end

  def show
    @event = Event.find(params[:id])
  end

  private

    def event_params
      params.require(:event).permit(:place, :date, :start)
    end

    def not_testing
      if current_employee.netID == 'test123'
        redirect_to '/test#index'
      end
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_cancel.html.erb
<%= form_for(current_employee.event_employees.find_by(event_id: @event.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Cancel", class: "btn btn-small" %>
<% end %>

app/views/events/_event.html.erb
<li>
  <% if current_employee.exec? %>
    <% approp_path = event %>
  <% else %>
    <% approp_path = edit_event_path(event.id) %>
  <% end %>
  <%= link_to event.place, approp_path %>
  <%= event.date.strftime("%B %e") %>
  <% if current_employee.exec? %>
    | <%= link_to "edit", edit_event_path(event.id) %>
    | <%= link_to "delete", event, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/events/_signup.html.erb
<%= form_for(current_employee.event_employees.build(event_id: @event.id)) do |f| %>
  <div><%= f.hidden_field :event_id %></div>
  <%= f.submit "I'm Available!", class: "btn btn-small btn-primary" %>
<% end %>

app/views/events/_signup_form.html.erb
<div id="signup_form">
  <% if current_employee.signed_up?(@event) %>
    <p>Thanks for letting us know you're availability! If you're selected to work this event, we will notify you by email on the day of the event (or earlier if possible).</p>
    <%= render 'cancel' %>
  <% else %>
    <%= render 'signup' %>
  <% end %>
</div>

app/views/events/edit.html.erb
<% @event = Event.find(params[:id]) %>
<% provide(:title, @event.place) %>

<% if current_employee.exec? %>
  <div class="row">
    <div class="event offset2">
      <%= form_for(@event) do |f| %>

        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :place %>
        <%= f.text_field :place %>

        <%= f.label :date %>
        <%= f.date_field :date %>

        <%= f.label :start %>
        <%= f.time_field :start %>

        <%= f.submit "Update event", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
<% else %>
  <% now = Time.new %>
  <% near_event_start = now.day == @event.date.day && now.month == @event.date.month && @event.start.hour - now.hour <= 1 %>
  <% if near_event_start %>
    <div class="row">
      <div class="event offset2">
        <h2>The team for this event has already been sent out!</h2>
        <h3>Why don't you check the events page and see there's another event you're available for?</h3>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="event offset2">
        <h2><%= @event.place %></h2>
        <h3><%= @event.date.strftime("%B %e") %></h3>
        <h3><%= @event.start.strftime("%l:%M") %></h3>
        <%= render 'signup_form' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/index.html.erb
<% provide(:title, 'All events') %>
<% @events = Event.paginate(page: params[:page]) %>
<h1>All posted events</h1>

<% will_paginate %>

<% if @events.any? %>
  <ul class="events">
    <%= render @events %>
  </ul>
<% else %>
  <div class="events">Nothing posted currently, check back soon!</div>
<% end %>

<% will_paginate %>

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>
<h1>Add a new event</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@event) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :place %>
    <%= f.text_field :place %>

    <%= f.label :date %>
    <%= f.date_field :date %>

    <%= f.label :start %>
    <%= f.time_field :start %>

    <%= f.submit "Add event", class: "btn btn-large btn-primary" %>
  <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% @event = Event.find(params[:id]) %>
<% provide(:title, @event.place) %>

<div class="row">
  <div class="event offset2">
    <h2><%= @event.place %></h2>
    <h3><%= @event.date.strftime("%B %e") %></h3>
    <h3><%= @event.start.strftime("%l:%M") %></h3>
    <% if @event.event_employees.any? %>
      <h4>Able to work:</h4>
    <% end %>
    <% @event.event_employees.each do |e| %>
      <h4>
        <%= e.employee.name %>
      </h4>
    <% end %>
  </div>
</div>