config/routes.rb
Schedulizer::Application.routes.draw do
  resources :events
  resources :employees
  resources :sessions, only: [:new, :create, :destroy]
  resources :event_employees, only: [:create, :destroy]
  resources :test
  root 'events#index'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/api/events', to: API::EventsAPIController.action(:index)
  post '/api/events/destroy', to: API::EventsAPIController.action(:destroy)
  post '/api/events/create', to: API::EventsAPIController.action(:create)
  post '/api/events/update', to: API::EventsAPIController.action(:update)
  get '/api/event_employees', to: API::EventEmployeesAPIController.action(:index)
  post '/api/event_employees/destroy', to: API::EventEmployeesAPIController.action(:destroy)
  post '/api/event_employees/create', to: API::EventEmployeesAPIController.action(:create)
  post '/api/event_employees/update', to: API::EventEmployeesAPIController.action(:update)

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :event_employees, foreign_key: "employee_id", dependent: :destroy
  has_many :events, through: :event_employees, source: :event
  has_secure_password
  before_save { netID.downcase! }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :netID, presence: true, uniqueness: { case_sensative: false }
  validates :password, length: { minimum: 6 }

  def Employee.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Employee.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def signed_up?(event)
    event_employees.find_by(event_id: event.id)
  end

  def signup!(event)
    event_employees.create!(event_id: event.id)
  end

  def cancel!(event)
    event_employees.find_by(event_id: event.id).destroy!
  end

  private

    def create_remember_token
      self.remember_token = Employee.encrypt(Employee.new_remember_token)
    end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_employees, foreign_key: "event_id", dependent: :destroy
  has_many :workers, through: :event_employees, source: :employee
  default_scope -> { order('date DESC') }
  validates :place, presence: true, length: { maximum: 100 }
  validates :date, presence: true
  validates :start, presence: true
end

app/models/event_employee.rb
class EventEmployee < ActiveRecord::Base
  belongs_to :event
  belongs_to :employee
  validates :event_id, presence: true
  validates :employee_id, presence: true
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, presence: true
  validates :email, format: { with: %r{.+@.+\..+}, allow_blank: true }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/news_story.rb
class NewsStory < ActiveRecord::Base
  validates :title, :snippet, :url, presence: true
end

app/models/test.rb
class Test < ActiveRecord::Base
  validates :link, presence: true
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :content, :author, presence: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :signed_in_employee
  before_action :correct_employee, only: [:edit, :update]
  before_action :exec, only: [:index, :new, :destroy]

  def index
    @employees = Employee.paginate(page: params[:page], per_page: 15)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = "Employee added to the system."
      redirect_to new_employee_path
    end
    
  end

  def edit
  end

  def update
    if @employee.update_attributes(employee_params)
      flash[:success] = "Password updated"
    end
    render 'edit'
  end

  def destroy
    Employee.find(params[:id]).destroy
    flash[:success] = "Employee removed from system."
    redirect_to employees_url
  end

  private

    def employee_params
      params.require(:employee).permit(:name, :netID, :password, 
                                       :password_confirmation, :exec)
    end

    # Before filters

    def correct_employee
      @employee = Employee.find(params[:id])
      redirect_to(root_url) unless current_employee?(@employee) || current_employee.exec?
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_employee
  before_action :exec, only: [:new, :create, :destroy]
  before_action :not_testing

  def index
    @events = Event.paginate(page: params[:page])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event added to calendar."
    end
    render 'index'
  end

  def edit
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
    end
    render 'index'
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to events_url
  end

  def show
    @event = Event.find(params[:id])
  end

  private

    def event_params
      params.require(:event).permit(:place, :date, :start)
    end

    def not_testing
      if current_employee.netID == 'test123'
        redirect_to '/test#index'
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    employee = Employee.find_by(netID: params[:session][:netID].downcase)
    if employee && employee.authenticate(params[:session][:password])
      sign_in employee
      redirect_back_or root_url
    else
      flash.now[:error] = 'Invalid netID/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  before_action :signed_in_employee

  def create
    @test = Test.new(testing_params)
  end

  def edit
  end

  def update
    if Test.find(1).update_attributes(testing_params)
      flash[:success] = "Testing status updated"
    end
    redirect_to edit_test_path(Test.find(1))
  end

  private

    def testing_params
      params.require(:test).permit(:link, :testingPeriod)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_stories_helper.rb
module NewsStoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(employee)
    remember_token = Employee.new_remember_token
    cookies.permanent[:remember_token] = remember_token if cookies
    employee.update_attribute(:remember_token, Employee.encrypt(remember_token))
    self.current_employee = employee
  end

  def signed_in?
    !current_employee.nil?
  end

  def current_employee=(employee)
    @current_employee = employee
  end

  def current_employee
    remember_token = Employee.encrypt(cookies[:remember_token])
    @current_employee ||= Employee.find_by(remember_token: remember_token)
  end

  def current_employee?(employee)
    employee == current_employee
  end

  def signed_in_employee
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in"
    end
  end

  def sign_out
    current_employee.update_attribute(:remember_token, Employee.encrypt(Employee.new_remember_token))
    cookies.delete(:remember_token)
    self.current_employee = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def exec
    redirect_to(root_url) unless current_employee.exec?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/layouts/_header.html.erb
<% @test = Test.find(1) %>

<header>
  <%= image_tag("transparentWithText.png") %>
  <% if signed_in? %>
    <nav class="nav nav-tabs">
      <% if current_employee.netID != 'test123' %>
        <li 
          <% if yield(:title) == "All events" %>
            class="active"
          <% end %>
            ><%= link_to "Events", events_path %></li>
        <% if current_employee.exec? %>
          <li 
            <% if yield(:title) == "All employees" %>
              class="active"
            <% end %>
              ><%= link_to "Employees", employees_path %></li>
          <li 
            <% if yield(:title) == "New Event" %>
              class="active"
            <% end %>
              ><%= link_to "Add Event", new_event_path %></li>
          <li 
            <% if yield(:title) == "New employee" %>
              class="active"
            <% end %>
              ><%= link_to "Add Employee", new_employee_path %></li>
        <% end %>
        <li 
          <% if yield(:title) == "Change password" %>
            class="active"
          <% end %>
            ><%= link_to "Change Password", edit_employee_path(current_employee) %></li>
      <% end %>
      <% if signed_in? && !current_employee.exec? %>
        <li><%= link_to "Testing", @test.link %></li>
      <% elsif signed_in? && current_employee.exec? %>
        <li><%= link_to "Testing", edit_test_path(@test) %></li>
      <% end %>
      <li><%= link_to "Log out", signout_path, method:"delete" %>
    </nav>
  <% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div id="container">
    <%= render 'layouts/header' %>
    <div id="content">
      <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>